### PR TITLE
New Functionality and bug fixing

### PR DESCRIPTION
**Pull request by crossleyjuan**
Hello,
I've added the following:

- Description to the reset method so developers understand that this overrides the date
- Fixed an important bug as the selector was not used and therefore it was not working with more than 1 picker
- Fixed some indentation recommended.
- Implemented the reset method so developer can change the current selected date.
- Implemented a new opts.selectedDate so developers can initialize the control with a date different than today.
- Added an index_multi.html to test the multi control.
-

### CODE REVIEW

**Comment by crossleyjuan** [comment]
I see you reverted some of the issues I've fixed, can you show an example on how to use more than 1 control on the same page? I found several issues with this, but I guess it's a bad usage from my side... if you put 3 in the same page the events are completely mixed up. please check https://github.com/priyank-p/simplepicker/pull/16/commits/dda513ce66cfc9631f79b19f30a6c8103b47e6d3 I think it will be good if you check your code with the index_multi.html I've added in https://github.com/priyank-p/simplepicker/pull/16/commits/b8ec4c7c0d28fda7d4f1b4eef70d2b55cf7721d4 so you can check what are the errors referring to.
Do you mind to give a look to my fork, and let me know if you can make it work with the multi control please?

**Comment by priyank-p** [comment]
@crossleyjuan I did look at all the commits you pushed to the master. I think I overlooked some of the code because you commit message we too long and unreadable sorry. Regarding this issue:
> on how to use more than 1 control on the same page?

By more than 1 control you mean multiple SimplePicker instances? They should work but let me try.
Also, this is a good situation to mention the importance of good commit messages. If it was something like this:
```
simplepicker: Fix an issue with having multiple instances of simplepicker.

There is a problem when there is more than one instance of simplepicker. (Description of the problem). (Then how your code fixes it if it not obvious from looking at the fix).
```

I would have been way easier to understand and integrate into the project.

**Comment by priyank-p** [comment]
I would also be happy to merge the `index_multi` page if it is helpful to you. I didn't find it helpful hence did not merge it.

**Comment by priyank-p** [comment]
(Also, I am active on https://chat.zulip.org if you want to have conversations there; PM me my name is Priyank Patel there)

**Comment by priyank-p** [comment]
Here is the reason I removed that commit. The change of the commit is:
```typescript
if (typeof elOrOpts === 'string') {
    el = elOrOpts as string;
} else if (typeof elOrOpts === 'object') {
```

The relevant background here is these changes is related to the argument passed to the constructor. I can explain more here if needed but if `elOrOpts` is a string then it means it an element but a selector. And if it is a selector then we need to use `document.querySelector` to get the element. If you just set `el` to string here the code below should throw an error.

**Pull request merged**
